## Setup Configuration
roboflow_url: "https://app.roboflow.com/ds/WXhb7XSaNb?key=B7P99J5E8P"
# D4MSLargeSet_No_Augmentation: https://app.roboflow.com/ds/WXhb7XSaNb?key=B7P99J5E8P
# D4MSLargeSet: https://app.roboflow.com/ds/ZT83hNUbvA?key=qC45ah4HO7
# Custom Data: https://app.roboflow.com/ds/DunlOIyiR4?key=uPXGckqBNa
# Custom + Synthetic: https://app.roboflow.com/ds/rS8HDRXsWw?key=4KOBv8fUbF
# python_packages(lists not supported): ['ultralytics', 'roboflow', 'uti
python_dir: "/mpac/dbax_pylib/"
global_epochs: 1


## Training Configuration for YOLOv8
project_train: "YOLOBDD"
experiment_train: "test_run"
data_dir: "/workspace/dataset/yolo_mots"
model: "yolov8n.pt"
batch: 64
epochs: 1
patience: 25
im_size: 640
device: 0
workers: 8
overwrite: False
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.005
warmup: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
fl_gamma: 0.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0


## Test Evalutaion Configuration Parameters
test_data_dir: "datasets/"
confidence: 0.001
iou: 0.6
save_json: True
project_test: "YSP"
experiment_test: "default_100_epochs"
